name: grouped_buttons
description: A simple package that makes grouping Checkboxes and Radio Buttons much easier.
version: 0.0.1
author: Akshath Jain
homepage: https://akshathjain.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
